version: '3.5'

services:

  node1:
    image: mysql:latest
    container_name: node1
    hostname: node1
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=pucsd
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  node2:
    image: mysql:latest
    container_name: node2
    hostname: node2
    ports:
      - "3308:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=pucsd
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20
    depends_on:
      - node1

  node3:
    image: mysql:latest
    container_name: node3
    hostname: node3
    ports:
      - "3309:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=pucsd
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20
    depends_on:
      - node2
